In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.1882, 0.5114, 0.7072],
        [0.6474, 0.9995, 0.7406],
        [0.7543, 0.7379, 0.6253],
        [0.8695, 0.6317, 0.7345],
        [0.7480, 0.0033, 0.1543]])


In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float) # same shape but value & dtype are changed
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1795, 0.1001, 0.6923],
        [0.1992, 0.0208, 0.5506],
        [0.1932, 0.8144, 0.0599],
        [0.3217, 0.6382, 0.5668],
        [0.7098, 0.7127, 0.0907]])


In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### Operation

In [10]:
y = torch.rand_like(x)

In [11]:
print(x.add(y))

tensor([[1.0036, 0.5596, 1.5338],
        [0.4603, 0.8497, 1.2412],
        [0.8947, 0.9249, 0.9021],
        [1.3022, 0.8633, 1.1996],
        [0.8097, 0.8522, 0.5715]])


In [12]:
print(x+y)

tensor([[1.0036, 0.5596, 1.5338],
        [0.4603, 0.8497, 1.2412],
        [0.8947, 0.9249, 0.9021],
        [1.3022, 0.8633, 1.1996],
        [0.8097, 0.8522, 0.5715]])


In [13]:
print(torch.add(x,y))

tensor([[1.0036, 0.5596, 1.5338],
        [0.4603, 0.8497, 1.2412],
        [0.8947, 0.9249, 0.9021],
        [1.3022, 0.8633, 1.1996],
        [0.8097, 0.8522, 0.5715]])


In [14]:
result = torch.empty_like(x)
torch.add(x,y,out=result)
print(result) 

tensor([[1.0036, 0.5596, 1.5338],
        [0.4603, 0.8497, 1.2412],
        [0.8947, 0.9249, 0.9021],
        [1.3022, 0.8633, 1.1996],
        [0.8097, 0.8522, 0.5715]])


#### in-place, functions end with '_' will be in place operation

In [15]:
y.add_(x)
print(y)

tensor([[1.0036, 0.5596, 1.5338],
        [0.4603, 0.8497, 1.2412],
        [0.8947, 0.9249, 0.9021],
        [1.3022, 0.8633, 1.1996],
        [0.8097, 0.8522, 0.5715]])


In [16]:
x[:,1]

tensor([0.1001, 0.0208, 0.8144, 0.6382, 0.7127])

#### tensor.view, similar with numpy.reshape

In [18]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### tensor.item(), get value of individual element

In [21]:
print(x[2,3])
x[2,3].item()

tensor(0.6465)


0.6464559435844421

#### more operations in pytorch [docs](https://pytorch.org/docs/torch)

### Converting to Numpy

In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### torch.from_numpy, convert to torch tensor

In [25]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### use tensor.to() to move tensor to any device, default based on cpu

In [26]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu"), torch.double)

tensor([[1.8309, 1.8118, 1.9887, 1.9989],
        [1.3132, 1.4968, 1.6439, 1.9391],
        [1.8525, 1.6731, 1.0260, 1.6465],
        [1.9526, 1.0103, 1.3860, 1.8066]], device='cuda:0')
tensor([[1.8309, 1.8118, 1.9887, 1.9989],
        [1.3132, 1.4968, 1.6439, 1.9391],
        [1.8525, 1.6731, 1.0260, 1.6465],
        [1.9526, 1.0103, 1.3860, 1.8066]]) torch.float64
